// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0P6Tg7y0uY9njsHTUOu6WmuQEWLA07m0',
    appId: '1:18899511322:web:50c1fd39faaca9c11b09a3',
    messagingSenderId: '18899511322',
    projectId: 'fir-test-843fa',
    authDomain: 'fir-test-843fa.firebaseapp.com',
    storageBucket: 'fir-test-843fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhBX4iP2ny7HjKmSAefzubXdmnEU5bp6Y',
    appId: '1:18899511322:android:2a5906fa3ef624201b09a3',
    messagingSenderId: '18899511322',
    projectId: 'fir-test-843fa',
    storageBucket: 'fir-test-843fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxui_KBViJJFUYaRp4-cVw4c7bsU01vQY',
    appId: '1:18899511322:ios:51116cc7ed0340791b09a3',
    messagingSenderId: '18899511322',
    projectId: 'fir-test-843fa',
    storageBucket: 'fir-test-843fa.appspot.com',
    iosBundleId: 'com.example.dmythra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxui_KBViJJFUYaRp4-cVw4c7bsU01vQY',
    appId: '1:18899511322:ios:f676d938dbc015541b09a3',
    messagingSenderId: '18899511322',
    projectId: 'fir-test-843fa',
    storageBucket: 'fir-test-843fa.appspot.com',
    iosBundleId: 'com.example.dmythra.RunnerTests',
  );
}
